ARG MAVEN_VERSION=<your maven version>-openjdk-<your openjdk version>-slim
ARG OPENJDK_VERSION=<your openjdk version>-jre-slim
ARG PORT=<your exposing port>



FROM maven:${MAVEN_VERSION} AS builder

COPY ./src  /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -Dmaven.test.skip=true




FROM openjdk:${OPENJDK_VERSION} AS runner
COPY --from=builder /home/app/target/*.jar /usr/local/lib/app.jar
EXPOSE ${PORT}
CMD ["java","-jar","/usr/local/lib/app.jar"]
